import { SettingOutlined, UserOutlined } from '@ant-design/icons';
import * as routes from 'router/routes/financialRoutes';
import * as keys from 'router/routeKeys/financialRoutesKeys';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faChartLine,
  faRandom,
  faExchangeAlt,
  faTasks,
  faFileInvoice,
  faFile,
  faChartBar,
  faMoneyBill1Wave,
} from '@fortawesome/free-solid-svg-icons';

export const sideMenu = [
  {
    name: 'Dashboard',
    key: keys.FINANCIAL_DASHBOARD_KEY,
    icon: <FontAwesomeIcon icon={faChartLine} />,
    url: routes.FINANCIAL_DASHBOARD,
    hasSubMenu: false,
    hasPermission: true,
    menu: [],
  },
  {
    name: 'User Rights',
    key: keys.FINANCIAL_RIGHTS,
    icon: <UserOutlined />,
    url: '',
    hasSubMenu: true,
    hasPermission: true,
    menu: [
      {
        name: 'Accounts',
        key: keys.FINANCIAL_RIGHTS_ACCOUNTS,
        icon: '',
        url: routes.USER_RIGHTS_ACCOUNTS,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Books',
        key: keys.FINANCIAL_RIGHTS_BOOKS,
        icon: '',
        url: routes.USER_RIGHTS_BOOKS,
        hasSubMenu: false,
        hasPermission: true,
      },
    ],
  },
  {
    name: 'Configurations',
    key: keys.FINANCIAL_CONFIG,
    icon: <SettingOutlined />,
    url: '',
    hasSubMenu: true,
    hasPermission: true,
    menu: [
      {
        name: 'Chart of Accounts',
        key: keys.FINANCIAL_CONFIG_COA,
        icon: '',
        url: routes.CONFIGURATIONS_COA,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Voucher Type',
        key: keys.FINANCIAL_CONFIG_VT,
        icon: '',
        url: routes.CONFIGURATIONS_VOUCHER_TYPES,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Books',
        key: keys.FINANCIAL_CONFIG_BOOKS,
        icon: '',
        url: routes.CONFIGURATIONS_BOOKS,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Sub Account Groups',
        key: keys.FINANCIAL_CONFIG_SAG,
        icon: '',
        url: routes.CONFIGURATIONS_SAG,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Sub Accounts',
        key: keys.FINANCIAL_CONFIG_SA,
        icon: '',
        url: routes.CONFIGURATIONS_SUB_ACCOUNTS,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Financial Year',
        key: keys.FINANCIAL_CONFIG_FY,
        icon: '',
        url: routes.CONFIGURATIONS_FY,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Financial Period',
        key: keys.FINANCIAL_CONFIG_FP,
        icon: '',
        url: routes.CONFIGURATIONS_FP,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Cheque Format',
        key: keys.FINANCIAL_CONFIG_CF,
        icon: '',
        url: routes.CONFIGURATIONS_CF,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Cash Master',
        key: keys.FINANCIAL_CONFIG_CM,
        icon: '',
        url: routes.CONFIGURATIONS_CM,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Bank Master',
        key: keys.FINANCIAL_CONFIG_BM,
        icon: '',
        url: routes.CONFIGURATIONS_BM,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Discount Policy',
        key: keys.FINANCIAL_CONFIG_DP,
        icon: '',
        url: routes.CONFIGURATIONS_DP,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'General Settings',
        key: keys.FINANCIAL_CONFIG_GS,
        icon: '',
        url: routes.CONFIGURATIONS_GS,
        hasSubMenu: false,
        hasPermission: true,
      },
    ],
  },
  {
    name: 'GL Transactions',
    key: keys.FINANCIAL_GLT,
    icon: <FontAwesomeIcon icon={faRandom} />,
    url: '',
    hasSubMenu: true,
    hasPermission: true,
    menu: [
      {
        name: 'Journal Vouchers',
        key: keys.FINANCIAL_GLT_JV,
        icon: '',
        url: `${routes.GLT_JV_FORM_BASE}/new`,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Cheque Printing',
        key: keys.FINANCIAL_GLT_CP,
        icon: '',
        url: routes.GLT_CP,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Period End Voucher',
        key: keys.FINANCIAL_GLT_PEV,
        icon: '',
        url: routes.GLT_PEV,
        hasSubMenu: false,
        hasPermission: true,
      },
    ],
  },
  {
    name: 'Payable Transactions',
    key: keys.FINANCIAL_PT,
    icon: <FontAwesomeIcon icon={faExchangeAlt} />,
    url: '',
    hasSubMenu: true,
    hasPermission: true,
    menu: [
      {
        name: 'Prepayment',
        key: keys.FINANCIAL_PT_PREPAYMENT,
        icon: '',
        url: routes.PT_PREPAYMENT,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Purchase Invoice',
        key: keys.FINANCIAL_PT_PI,
        icon: '',
        url: routes.PT_PURCHASE_INVOICE,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Payment',
        key: keys.FINANCIAL_PT_PAYMENT,
        icon: '',
        url: routes.PT_PAYMENT,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Debit & Credit Note',
        key: keys.FINANCIAL_PT_DC_NOTE,
        icon: '',
        url: routes.PT_DC_NOTE,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Refund',
        key: keys.FINANCIAL_PT_REFUND,
        icon: '',
        url: routes.PT_REFUND,
        hasSubMenu: false,
        hasPermission: true,
      },
    ],
  },
  {
    name: 'Payable Reports',
    key: keys.FINANCIAL_PR,
    icon: <FontAwesomeIcon icon={faTasks} />,
    url: '',
    hasSubMenu: true,
    hasPermission: true,
    menu: [
      {
        name: 'Vendor Ledger',
        key: keys.FINANCIAL_PR_VL,
        icon: '',
        url: routes.PR_VENDOR_LEDGER,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Vendor Aging',
        key: keys.FINANCIAL_PR_VA,
        icon: '',
        url: routes.PR_VENDOR_AGING,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Payment Summary',
        key: keys.FINANCIAL_PR_PS,
        icon: '',
        url: routes.PR_PAYMENT_SUMMARY,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Invoice Summary',
        key: keys.FINANCIAL_PR_IS,
        icon: '',
        url: routes.PR_INVOICE_SUMMARY,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Knocked Prepayments',
        key: keys.FINANCIAL_PR_KP,
        icon: '',
        url: routes.PR_KNOCKED_PREPAYMENTS,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Invoices Outstanding',
        key: keys.FINANCIAL_PR_IO,
        icon: '',
        url: routes.PR_INVOICES_OUTSTANDING,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Vendor Summary',
        key: keys.FINANCIAL_PR_VS,
        icon: '',
        url: routes.PR_VENDOR_SUMMARY,
        hasSubMenu: false,
        hasPermission: true,
      },
    ],
  },
  {
    name: 'Receivable Transactions',
    key: keys.FINANCIAL_RT,
    icon: <FontAwesomeIcon icon={faFileInvoice} />,
    url: '',
    hasSubMenu: true,
    hasPermission: true,
    menu: [
      {
        name: 'Prepayment',
        key: keys.FINANCIAL_RT_PREPAYMENT,
        icon: '',
        url: routes.RT_PREPAYMENT,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Sale Invoice',
        key: keys.FINANCIAL_RT_SI,
        icon: '',
        url: routes.RT_SI,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Receipt',
        key: keys.FINANCIAL_RT_RECEIPT,
        icon: '',
        url: routes.RT_RECEIPT,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Debit & Credit Note',
        key: keys.FINANCIAL_RT_DC_NOTE,
        icon: '',
        url: routes.RT_DC_NOTE,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Refund Bank',
        key: keys.FINANCIAL_RT_RB,
        icon: '',
        url: routes.RT_REFUND_BANK,
        hasSubMenu: false,
        hasPermission: true,
      },
    ],
  },
  {
    name: 'Receivable Reports',
    key: keys.FINANCIAL_RR,
    icon: <FontAwesomeIcon icon={faTasks} />,
    url: '',
    hasSubMenu: true,
    hasPermission: true,
    menu: [
      {
        name: 'Payment Summary',
        key: keys.FINANCIAL_RR_PS,
        icon: '',
        url: routes.RR_PAYMENT_SUMMARY,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Sale Detail',
        key: keys.FINANCIAL_RR_SD,
        icon: '',
        url: routes.RR_SALE_DETAIL,
        hasSubMenu: false,
        hasPermission: true,
      },
    ],
  },
  {
    name: 'General Reports',
    key: keys.FINANCIAL_GR,
    icon: <FontAwesomeIcon icon={faFile} />,
    url: '',
    hasSubMenu: true,
    hasPermission: true,
    menu: [
      {
        name: 'Chart Of Accounts',
        key: keys.FINANCIAL_GR_COA,
        icon: '',
        url: routes.GR_COA,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Journal Voucher',
        key: keys.FINANCIAL_GR_JV,
        icon: '',
        url: routes.GR_JV,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'General Ledger',
        key: keys.FINANCIAL_GR_GL,
        icon: '',
        url: routes.GR_GL,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Sub Ledger',
        key: keys.FINANCIAL_GR_SL,
        icon: '',
        url: routes.GR_SL,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Trial Balance',
        key: keys.FINANCIAL_GR_TB,
        icon: '',
        url: routes.GR_TB,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Profit/Loss Report',
        key: keys.FINANCIAL_GR_PLR,
        icon: '',
        url: routes.GR_PLR,
        hasSubMenu: false,
        hasPermission: true,
      },
    ],
  },
  {
    name: 'Financial Reports',
    key: keys.FINANCIAL_FR,
    icon: <FontAwesomeIcon icon={faChartBar} />,
    url: '',
    hasSubMenu: true,
    hasPermission: true,
    menu: [
      {
        name: 'Financial Period Template',
        key: keys.FINANCIAL_FR_FPT,
        icon: '',
        url: routes.FR_FPT,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'User Defined Final AC',
        key: keys.FINANCIAL_FR_FAC,
        icon: '',
        url: routes.FR_FAC,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Financial Report',
        key: keys.FINANCIAL_FR_FR,
        icon: '',
        url: routes.FR_FR,
        hasSubMenu: false,
        hasPermission: true,
      },
    ],
  },
  {
    name: 'Budgeting',
    key: keys.FINANCIAL_BUDGETING,
    icon: <FontAwesomeIcon icon={faMoneyBill1Wave} />,
    url: '',
    hasSubMenu: true,
    hasPermission: true,
    menu: [
      {
        name: 'Department Budget',
        key: keys.FINANCIAL_BUDGETING_DB,
        icon: '',
        url: routes.BUDGETING_DB,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Budget Report',
        key: keys.FINANCIAL_BUDGETING_BR,
        icon: '',
        url: routes.BUDGETING_BR,
        hasSubMenu: false,
        hasPermission: true,
      },
    ],
  },
];
