import { SettingOutlined } from '@ant-design/icons';
import * as routes from 'router/routes/inventoryRoutes';
import * as keys from 'router/routeKeys/inventoryKeys';

export const sideMenu = [
  {
    name: 'Admin',
    key: keys.INVENTORY_ADMIN,
    icon: <SettingOutlined />,
    url: '',
    hasSubMenu: true,
    hasPermission: true,
    menu: [
      {
        name: 'User Stores',
        key: keys.INVENTORY_ADMIN_USER_STORES,
        icon: '',
        url: routes.ADMIN_USER_STORES,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'User Transaction',
        key: keys.INVENTORY_ADMIN_UT,
        icon: '',
        url: routes.ADMIN_UT,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'User Sale Stores',
        key: keys.INVENTORY_ADMIN_USS,
        icon: '',
        url: routes.ADMIN_USS,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'User Cost Center',
        key: keys.INVENTORY_ADMIN_UCC,
        icon: '',
        url: routes.ADMIN_UCC,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'User Stores Transaction',
        key: keys.INVENTORY_ADMIN_UST,
        icon: '',
        url: routes.ADMIN_UST,
        hasSubMenu: false,
        hasPermission: true,
      },
    ],
  },
  {
    name: 'Definition',
    key: keys.INVENTORY_DEFINITION,
    icon: <SettingOutlined />,
    url: '',
    hasSubMenu: true,
    hasPermission: true,
    menu: [
      {
        name: 'Store',
        key: keys.INVENTORY_DEFINITION_STORE,
        icon: '',
        url: routes.DEFINITION_STORE,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Manufacturer',
        key: keys.INVENTORY_DEFINITION_MANUFACTURER,
        icon: '',
        url: routes.DEFINITION_MANUFACTURER,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Vendor',
        key: keys.INVENTORY_DEFINITION_VENDOR,
        icon: '',
        url: routes.DEFINITION_VENDOR,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Item',
        key: keys.INVENTORY_DEFINITION_ITEM,
        icon: '',
        url: routes.DEFINITION_ITEM,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Item Detail',
        key: keys.INVENTORY_DEFINITION_ITEM_DETAIL,
        icon: '',
        url: routes.DEFINITION_ITEM_DETAIL,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Store Items',
        key: keys.INVENTORY_DEFINITION_STORE_ITEMS,
        icon: '',
        url: routes.DEFINITION_STORE_ITEMS,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Tax Type',
        key: keys.INVENTORY_DEFINITION_TAX_TYPE,
        icon: '',
        url: routes.DEFINITION_TAX_TYPE,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Tax Type Detail',
        key: keys.INVENTORY_DEFINITION_TTD,
        icon: '',
        url: routes.DEFINITION_TTD,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Authority Amount Limits',
        key: keys.INVENTORY_DEFINITION_AAL,
        icon: '',
        url: routes.DEFINITION_AAL,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Requisition Authority Amount Limits',
        key: keys.INVENTORY_DEFINITION_RAAL,
        icon: '',
        url: routes.DEFINITION_RAAL,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Vendor Items',
        key: keys.INVENTORY_DEFINITION_VI,
        icon: '',
        url: routes.DEFINITION_VI,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Generic Names',
        key: keys.INVENTORY_DEFINITION_GN,
        icon: '',
        url: routes.DEFINITION_GN,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Items Vendor List',
        key: keys.INVENTORY_DEFINITION_IVL,
        icon: '',
        url: routes.DEFINITION_IVL,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Vendor Term',
        key: keys.INVENTORY_DEFINITION_VT,
        icon: '',
        url: routes.DEFINITION_VT,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Drug Form',
        key: keys.INVENTORY_DEFINITION_DF,
        icon: '',
        url: routes.DEFINITION_DF,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Set Item MPR',
        key: keys.INVENTORY_DEFINITION_SIM,
        icon: '',
        url: routes.DEFINITION_SIM,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Customer',
        key: keys.INVENTORY_DEFINITION_CUSTOMER,
        icon: '',
        url: routes.DEFINITION_CUSTOMER,
        hasSubMenu: false,
        hasPermission: true,
      },
    ],
  },
  {
    name: 'Transaction',
    key: keys.INVENTORY_TRANSACTION,
    icon: <SettingOutlined />,
    url: '',
    hasSubMenu: true,
    hasPermission: true,
    menu: [
      {
        name: 'Purchase Requisition',
        key: keys.INVENTORY_TRANSACTION_PR,
        icon: '',
        url: routes.TRANSACTION_PR,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Purchase Requisition Authorities',
        key: keys.INVENTORY_TRANSACTION_PRA,
        icon: '',
        url: routes.TRANSACTION_PRA,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Generate Auto Requisitions',
        key: keys.INVENTORY_TRANSACTION_GAR,
        icon: '',
        url: routes.TRANSACTION_GAR,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Purchase Order',
        key: keys.INVENTORY_TRANSACTION_PO,
        icon: '',
        url: routes.TRANSACTION_PO,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Purchase Order Closing',
        key: keys.INVENTORY_TRANSACTION_POC,
        icon: '',
        url: routes.TRANSACTION_POC,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Purchase Order Authorities',
        key: keys.INVENTORY_TRANSACTION_POA,
        icon: '',
        url: routes.TRANSACTION_POA,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Material Inspection Note',
        key: keys.INVENTORY_TRANSACTION_MIN,
        icon: '',
        url: routes.TRANSACTION_MIN,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Store Receipt Note',
        key: keys.INVENTORY_TRANSACTION_SRN,
        icon: '',
        url: routes.TRANSACTION_SRN,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Purchase Return Note',
        key: keys.INVENTORY_TRANSACTION_PRN,
        icon: '',
        url: routes.TRANSACTION_PRN,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Internal Transfer Request',
        key: keys.INVENTORY_TRANSACTION_ITR,
        icon: '',
        url: routes.TRANSACTION_ITR,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Internal Store Issuance',
        key: keys.INVENTORY_TRANSACTION_ISI,
        icon: '',
        url: routes.TRANSACTION_ISI,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Internal Store Receipt',
        key: keys.INVENTORY_TRANSACTION_ISR,
        icon: '',
        url: routes.TRANSACTION_ISR,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Sale Return Note',
        key: keys.INVENTORY_TRANSACTION_SALE_RETURN_NOTE,
        icon: '',
        url: routes.TRANSACTION_SALE_RETURN_NOTE,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Sale Issue Note',
        key: keys.INVENTORY_TRANSACTION_SIN,
        icon: '',
        url: routes.TRANSACTION_SIN,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Store Adjustment Note',
        key: keys.INVENTORY_TRANSACTION_SAN,
        icon: '',
        url: routes.TRANSACTION_SAN,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Value Adjustment Note',
        key: keys.INVENTORY_TRANSACTION_VAN,
        icon: '',
        url: routes.TRANSACTION_VAN,
        hasSubMenu: false,
        hasPermission: true,
      },
    ],
  },
  {
    name: 'Reports/General',
    key: keys.INVENTORY_REPORTS,
    icon: <SettingOutlined />,
    url: '',
    hasSubMenu: true,
    hasPermission: true,
    menu: [
      {
        name: 'Store Wise Item Movement',
        key: keys.INVENTORY_REPORTS_SWIM,
        icon: '',
        url: routes.REPORTS_SWIM,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Expiry Wise Item List',
        key: keys.INVENTORY_REPORTS_EWIL,
        icon: '',
        url: routes.REPORTS_EWIL,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Expiry Wise - Vendor',
        key: keys.INVENTORY_REPORTS_EWV,
        icon: '',
        url: routes.REPORTS_EWV,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Store Item Summary',
        key: keys.INVENTORY_REPORTS_SIS,
        icon: '',
        url: routes.REPORTS_SIS,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Stock Position Batch Wise',
        key: keys.INVENTORY_REPORTS_SPBW,
        icon: '',
        url: routes.REPORTS_SPBW,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Stock Position Barcode',
        key: keys.INVENTORY_REPORTS_SPB,
        icon: '',
        url: routes.REPORTS_SPB,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Shift Management',
        key: keys.INVENTORY_REPORTS_SM,
        icon: '',
        url: routes.REPORTS_SPM,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Manufacturer Wise Stock Position',
        key: keys.INVENTORY_REPORTS_MWSP,
        icon: '',
        url: routes.REPORTS_MWSP,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Stock Summary Report',
        key: keys.INVENTORY_REPORTS_SSR,
        icon: '',
        url: routes.REPORTS_SSR,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Transaction Tracking Report',
        key: keys.INVENTORY_REPORTS_TTR,
        icon: '',
        url: routes.REPORTS_TTR,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Purchase Summary Report',
        key: keys.INVENTORY_REPORTS_PSR,
        icon: '',
        url: routes.REPORTS_PSR,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Transaction Valuation',
        key: keys.INVENTORY_REPORTS_TV,
        icon: '',
        url: routes.REPORTS_TV,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Item Value Category Wise',
        key: keys.INVENTORY_REPORTS_IVCW,
        icon: '',
        url: routes.REPORTS_IVCW,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Forecast Report',
        key: keys.INVENTORY_REPORTS_FR,
        icon: '',
        url: routes.REPORTS_FR,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'UnSold Items Report',
        key: keys.INVENTORY_REPORTS_UIR,
        icon: '',
        url: routes.REPORTS_UIR,
        hasSubMenu: false,
        hasPermission: true,
      },
    ],
  },
  {
    name: 'POS',
    key: keys.INVENTORY_POS,
    icon: <SettingOutlined />,
    url: '',
    hasSubMenu: true,
    hasPermission: true,
    menu: [
      {
        name: 'Sales',
        key: keys.INVENTORY_POS_SALES,
        icon: '',
        url: routes.POS_SALES,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Sales Return',
        key: keys.INVENTORY_POS_SR,
        icon: '',
        url: routes.POS_SR,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Open Shift',
        key: keys.INVENTORY_POS_OS,
        icon: '',
        url: routes.POS_OS,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Shift Management',
        key: keys.INVENTORY_POS_SM,
        icon: '',
        url: routes.POS_SM,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Sale Summary Report',
        key: keys.INVENTORY_POS_SSR,
        icon: '',
        url: routes.POS_SSR,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Item Wise Sale Report',
        key: keys.INVENTORY_POS_IWSR,
        icon: '',
        url: routes.POS_IWSR,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Items On Demand',
        key: keys.INVENTORY_POS_IOD,
        icon: '',
        url: routes.POS_IOD,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Items Shortage',
        key: keys.INVENTORY_POS_IS,
        icon: '',
        url: routes.POS_IS,
        hasSubMenu: false,
        hasPermission: true,
      },
    ],
  },
];
