const AMS_MANAGE_USERS = 'AMS_MANAGE_USERS';
const AMS_MANAGE_ROLES = 'AMS_MANAGE_ROLES';
const AMS_USER_TYPES = 'AMS_USER_TYPES';
const AMS_DEPARTMENTS = 'AMS_DEPARTMENTS';
const AMS_COST_CENTRE = 'AMS_COST_CENTRE';
const AMS_SITES = 'AMS_SITES';

export {
  AMS_MANAGE_USERS,
  AMS_MANAGE_ROLES,
  AMS_USER_TYPES,
  AMS_DEPARTMENTS,
  AMS_COST_CENTRE,
  AMS_SITES,
};
