const FINANCIAL_DASHBOARD_KEY = 'FINANCIAL_DASHBOARD';

const FINANCIAL_RIGHTS = 'FINANCIAL_RIGHTS';
const FINANCIAL_RIGHTS_ACCOUNTS = 'FINANCIAL_RIGHTS_ACCOUNTS';
const FINANCIAL_RIGHTS_BOOKS = 'FINANCIAL_RIGHTS_BOOKS';

const FINANCIAL_CONFIG = 'FINANCIAL_CONFIG';
const FINANCIAL_CONFIG_COA = 'FINANCIAL_CONFIG_COA';
const FINANCIAL_CONFIG_VT = 'FINANCIAL_CONFIG_VT';
const FINANCIAL_CONFIG_BOOKS = 'FINANCIAL_CONFIG_BOOKS';
const FINANCIAL_CONFIG_SAG = 'FINANCIAL_CONFIG_SAG';
const FINANCIAL_CONFIG_SA = 'FINANCIAL_CONFIG_SA';
const FINANCIAL_CONFIG_FY = 'FINANCIAL_CONFIG_FY';
const FINANCIAL_CONFIG_FP = 'FINANCIAL_CONFIG_FP';
const FINANCIAL_CONFIG_CF = 'FINANCIAL_CONFIG_CF';
const FINANCIAL_CONFIG_CM = 'FINANCIAL_CONFIG_CM';
const FINANCIAL_CONFIG_BM = 'FINANCIAL_CONFIG_BM';
const FINANCIAL_CONFIG_DP = 'FINANCIAL_CONFIG_DP';
const FINANCIAL_CONFIG_GS = 'FINANCIAL_CONFIG_GS';

const FINANCIAL_GLT = 'FINANCIAL_GLT';
const FINANCIAL_GLT_JV = 'FINANCIAL_GLT_JV';
const FINANCIAL_GLT_CP = 'FINANCIAL_GLT_CP';
const FINANCIAL_GLT_PEV = 'FINANCIAL_GLT_PEV';

const FINANCIAL_PT = 'FINANCIAL_PT';
const FINANCIAL_PT_PREPAYMENT = 'FINANCIAL_PT_PREPAYMENT';
const FINANCIAL_PT_PI = 'FINANCIAL_PT_PI';
const FINANCIAL_PT_PAYMENT = 'FINANCIAL_PT_PAYMENT';
const FINANCIAL_PT_DC_NOTE = 'FINANCIAL_PT_DC_NOTE';
const FINANCIAL_PT_REFUND = 'FINANCIAL_PT_REFUND';

const FINANCIAL_PR = 'FINANCIAL_PR';
const FINANCIAL_PR_VL = 'FINANCIAL_PR_VL';
const FINANCIAL_PR_VA = 'FINANCIAL_PR_VA';
const FINANCIAL_PR_PS = 'FINANCIAL_PR_PS';
const FINANCIAL_PR_IS = 'FINANCIAL_PR_IS';
const FINANCIAL_PR_KP = 'FINANCIAL_PR_KP';
const FINANCIAL_PR_IO = 'FINANCIAL_PR_IO';
const FINANCIAL_PR_VS = 'FINANCIAL_PR_VS';

const FINANCIAL_RT = 'FINANCIAL_RT';
const FINANCIAL_RT_PREPAYMENT = 'FINANCIAL_RT_PREPAYMENT';
const FINANCIAL_RT_SI = 'FINANCIAL_RT_SI';
const FINANCIAL_RT_RECEIPT = 'FINANCIAL_RT_RECEIPT';
const FINANCIAL_RT_DC_NOTE = 'FINANCIAL_RT_DC_NOTE';
const FINANCIAL_RT_RB = 'FINANCIAL_RT_RB';

const FINANCIAL_RR = 'FINANCIAL_RR';
const FINANCIAL_RR_PS = 'FINANCIAL_RR_PS';
const FINANCIAL_RR_SD = 'FINANCIAL_RR_SD';

const FINANCIAL_GR = 'FINANCIAL_GR';
const FINANCIAL_GR_COA = 'FINANCIAL_GR_COA';
const FINANCIAL_GR_JV = 'FINANCIAL_GR_JV';
const FINANCIAL_GR_GL = 'FINANCIAL_GR_GL';
const FINANCIAL_GR_SL = 'FINANCIAL_GR_SL';
const FINANCIAL_GR_TB = 'FINANCIAL_GR_TB';
const FINANCIAL_GR_PLR = 'FINANCIAL_GR_PLR';

const FINANCIAL_FR = 'FINANCIAL_FR';
const FINANCIAL_FR_FPT = 'FINANCIAL_FR_FPT';
const FINANCIAL_FR_FAC = 'FINANCIAL_FR_FAC';
const FINANCIAL_FR_FR = 'FINANCIAL_FR_FR';

const FINANCIAL_BUDGETING = 'FINANCIAL_BUDGETING';
const FINANCIAL_BUDGETING_DB = 'FINANCIAL_BUDGETING_DB';
const FINANCIAL_BUDGETING_BR = 'FINANCIAL_BUDGETING_BR';

export {
  FINANCIAL_DASHBOARD_KEY,
  FINANCIAL_RIGHTS,
  FINANCIAL_RIGHTS_ACCOUNTS,
  FINANCIAL_RIGHTS_BOOKS,
  FINANCIAL_CONFIG,
  FINANCIAL_CONFIG_COA,
  FINANCIAL_CONFIG_VT,
  FINANCIAL_CONFIG_BOOKS,
  FINANCIAL_CONFIG_SAG,
  FINANCIAL_CONFIG_SA,
  FINANCIAL_CONFIG_FY,
  FINANCIAL_CONFIG_FP,
  FINANCIAL_CONFIG_CF,
  FINANCIAL_CONFIG_CM,
  FINANCIAL_CONFIG_BM,
  FINANCIAL_CONFIG_DP,
  FINANCIAL_CONFIG_GS,
  FINANCIAL_GLT,
  FINANCIAL_GLT_JV,
  FINANCIAL_GLT_CP,
  FINANCIAL_GLT_PEV,
  FINANCIAL_PT,
  FINANCIAL_PT_PREPAYMENT,
  FINANCIAL_PT_PI,
  FINANCIAL_PT_PAYMENT,
  FINANCIAL_PT_DC_NOTE,
  FINANCIAL_PT_REFUND,
  FINANCIAL_PR,
  FINANCIAL_PR_VL,
  FINANCIAL_PR_VA,
  FINANCIAL_PR_PS,
  FINANCIAL_PR_IS,
  FINANCIAL_PR_KP,
  FINANCIAL_PR_IO,
  FINANCIAL_PR_VS,
  FINANCIAL_RT,
  FINANCIAL_RT_PREPAYMENT,
  FINANCIAL_RT_SI,
  FINANCIAL_RT_RECEIPT,
  FINANCIAL_RT_DC_NOTE,
  FINANCIAL_RT_RB,
  FINANCIAL_RR,
  FINANCIAL_RR_PS,
  FINANCIAL_RR_SD,
  FINANCIAL_GR,
  FINANCIAL_GR_COA,
  FINANCIAL_GR_JV,
  FINANCIAL_GR_GL,
  FINANCIAL_GR_SL,
  FINANCIAL_GR_TB,
  FINANCIAL_GR_PLR,
  FINANCIAL_FR,
  FINANCIAL_FR_FPT,
  FINANCIAL_FR_FAC,
  FINANCIAL_FR_FR,
  FINANCIAL_BUDGETING,
  FINANCIAL_BUDGETING_DB,
  FINANCIAL_BUDGETING_BR,
};
