const LOGIN_KEY = 'LOGIN';

const DEFAULT_HOME = 'DEFAULT_HOME';
const DEFAULT_AMS = 'DEFAULT_AMS';
const DEFAULT_FINANCIAL = 'DEFAULT_FINANCIAL';
const DEFAULT_INVENTORY = 'DEFAULT_INVENTORY';
const DEFAULT_HUMAN_RESOURCES = 'DEFAULT_HUMAN_RESOURCES';
const DEFAULT_PAYROLL = 'DEFAULT_PAYROLL';
const DEFAULT_GROUP_CONSOLIDATION = 'DEFAULT_GROUP_CONSOLIDATION';
const DEFAULT_PRODUCTION_PLANNING = 'DEFAULT_PRODUCTION_PLANNING';
const DEFAULT_RAW_MATERIAL = 'DEFAULT_RAW_MATERIAL';
const DEFAULT_COSTING = 'DEFAULT_COSTING';
const DEFAULT_TRANSPORTATION = 'DEFAULT_TRANSPORTATION';
const DEFAULT_QUALITY_CONTROL = 'DEFAULT_QUALITY_CONTROL';
const DEFAULT_VISITOR_MANAGEMENT = 'DEFAULT_VISITOR_MANAGEMENT';
const DEFAULT_VISITOR_FIXED_ASSETS = 'DEFAULT_VISITOR_FIXED_ASSETS';

export {
  LOGIN_KEY,
  DEFAULT_HOME,
  DEFAULT_AMS,
  DEFAULT_FINANCIAL,
  DEFAULT_INVENTORY,
  DEFAULT_HUMAN_RESOURCES,
  DEFAULT_PAYROLL,
  DEFAULT_GROUP_CONSOLIDATION,
  DEFAULT_PRODUCTION_PLANNING,
  DEFAULT_RAW_MATERIAL,
  DEFAULT_COSTING,
  DEFAULT_TRANSPORTATION,
  DEFAULT_QUALITY_CONTROL,
  DEFAULT_VISITOR_MANAGEMENT,
  DEFAULT_VISITOR_FIXED_ASSETS,
};
