const INVENTORY_ADMIN = 'INVENTORY_ADMIN';
const INVENTORY_ADMIN_USER_STORES = 'INVENTORY_ADMIN_USER_STORES';
const INVENTORY_ADMIN_UT = 'INVENTORY_ADMIN_UT';
const INVENTORY_ADMIN_USS = 'INVENTORY_ADMIN_USS';
const INVENTORY_ADMIN_UCC = 'INVENTORY_ADMIN_UCC';
const INVENTORY_ADMIN_UST = 'INVENTORY_ADMIN_UST';

const INVENTORY_DEFINITION = 'INVENTORY_DEFINITION';
const INVENTORY_DEFINITION_STORE = 'INVENTORY_DEFINITION_STORE';
const INVENTORY_DEFINITION_MANUFACTURER = 'INVENTORY_DEFINITION_MANUFACTURER';
const INVENTORY_DEFINITION_VENDOR = 'INVENTORY_DEFINITION_VENDOR';
const INVENTORY_DEFINITION_ITEM = 'INVENTORY_DEFINITION_ITEM';
const INVENTORY_DEFINITION_ITEM_DETAIL = 'INVENTORY_DEFINITION_ITEM_DETAIL';
const INVENTORY_DEFINITION_STORE_ITEMS = 'INVENTORY_DEFINITION_STORE_ITEMS';
const INVENTORY_DEFINITION_TAX_TYPE = 'INVENTORY_DEFINITION_TAX_TYPE';
const INVENTORY_DEFINITION_TTD = 'INVENTORY_DEFINITION_TTD';
const INVENTORY_DEFINITION_AAL = 'INVENTORY_DEFINITION_AAL';
const INVENTORY_DEFINITION_RAAL = 'INVENTORY_DEFINITION_RAAL';
const INVENTORY_DEFINITION_VI = 'INVENTORY_DEFINITION_VI';
const INVENTORY_DEFINITION_GN = 'INVENTORY_DEFINITION_GN';
const INVENTORY_DEFINITION_IVL = 'INVENTORY_DEFINITION_IVL';
const INVENTORY_DEFINITION_VT = 'INVENTORY_DEFINITION_VT';
const INVENTORY_DEFINITION_DF = 'INVENTORY_DEFINITION_DF';
const INVENTORY_DEFINITION_SIM = 'INVENTORY_DEFINITION_SIM';
const INVENTORY_DEFINITION_CUSTOMER = 'INVENTORY_DEFINITION_CUSTOMER';

const INVENTORY_TRANSACTION = 'INVENTORY_TRANSACTION';
const INVENTORY_TRANSACTION_PR = 'INVENTORY_TRANSACTION_PR';
const INVENTORY_TRANSACTION_PRA = 'INVENTORY_TRANSACTION_PRA';
const INVENTORY_TRANSACTION_GAR = 'INVENTORY_TRANSACTION_GAR';
const INVENTORY_TRANSACTION_PO = 'INVENTORY_TRANSACTION_PO';
const INVENTORY_TRANSACTION_POC = 'INVENTORY_TRANSACTION_POC';
const INVENTORY_TRANSACTION_POA = 'INVENTORY_TRANSACTION_POA';
const INVENTORY_TRANSACTION_MIN = 'INVENTORY_TRANSACTION_MIN';
const INVENTORY_TRANSACTION_SRN = 'INVENTORY_TRANSACTION_SRN';
const INVENTORY_TRANSACTION_PRN = 'INVENTORY_TRANSACTION_PRN';
const INVENTORY_TRANSACTION_ITR = 'INVENTORY_TRANSACTION_ITR';
const INVENTORY_TRANSACTION_ISI = 'INVENTORY_TRANSACTION_ISI';
const INVENTORY_TRANSACTION_ISR = 'INVENTORY_TRANSACTION_ISR';
const INVENTORY_TRANSACTION_SALE_RETURN_NOTE = 'INVENTORY_TRANSACTION_SALE_RETURN_NOTE';
const INVENTORY_TRANSACTION_SIN = 'INVENTORY_TRANSACTION_SIN';
const INVENTORY_TRANSACTION_SAN = 'INVENTORY_TRANSACTION_SAN';
const INVENTORY_TRANSACTION_VAN = 'INVENTORY_TRANSACTION_VAN';

const INVENTORY_REPORTS = 'INVENTORY_REPORTS';
const INVENTORY_REPORTS_SWIM = 'INVENTORY_REPORTS_SWIM';
const INVENTORY_REPORTS_EWIL = 'INVENTORY_REPORTS_EWIL';
const INVENTORY_REPORTS_EWV = 'INVENTORY_REPORTS_EWV';
const INVENTORY_REPORTS_SIS = 'INVENTORY_REPORTS_SIS';
const INVENTORY_REPORTS_SPBW = 'INVENTORY_REPORTS_SPBW';
const INVENTORY_REPORTS_SPB = 'INVENTORY_REPORTS_SPB';
const INVENTORY_REPORTS_SM = 'INVENTORY_REPORTS_SM';
const INVENTORY_REPORTS_MWSP = 'INVENTORY_REPORTS_MWSP';
const INVENTORY_REPORTS_SSR = 'INVENTORY_REPORTS_SSR';
const INVENTORY_REPORTS_TTR = 'INVENTORY_REPORTS_TTR';
const INVENTORY_REPORTS_PSR = 'INVENTORY_REPORTS_PSR';
const INVENTORY_REPORTS_TV = 'INVENTORY_REPORTS_TV';
const INVENTORY_REPORTS_IVCW = 'INVENTORY_REPORTS_IVCW';
const INVENTORY_REPORTS_FR = 'INVENTORY_REPORTS_FR';
const INVENTORY_REPORTS_UIR = 'INVENTORY_REPORTS_UIR';

const INVENTORY_POS = 'INVENTORY_POS';
const INVENTORY_POS_SALES = 'INVENTORY_POS_SALES';
const INVENTORY_POS_SR = 'INVENTORY_POS_SR';
const INVENTORY_POS_OS = 'INVENTORY_POS_OS';
const INVENTORY_POS_SM = 'INVENTORY_POS_SM';
const INVENTORY_POS_SSR = 'INVENTORY_POS_SSR';
const INVENTORY_POS_IWSR = 'INVENTORY_POS_IWSR';
const INVENTORY_POS_IOD = 'INVENTORY_POS_IOD';
const INVENTORY_POS_IS = 'INVENTORY_POS_IS';

export {
  INVENTORY_ADMIN,
  INVENTORY_ADMIN_USER_STORES,
  INVENTORY_ADMIN_UT,
  INVENTORY_ADMIN_USS,
  INVENTORY_ADMIN_UCC,
  INVENTORY_ADMIN_UST,
  INVENTORY_DEFINITION,
  INVENTORY_DEFINITION_STORE,
  INVENTORY_DEFINITION_MANUFACTURER,
  INVENTORY_DEFINITION_VENDOR,
  INVENTORY_DEFINITION_ITEM,
  INVENTORY_DEFINITION_ITEM_DETAIL,
  INVENTORY_DEFINITION_STORE_ITEMS,
  INVENTORY_DEFINITION_TAX_TYPE,
  INVENTORY_DEFINITION_TTD,
  INVENTORY_DEFINITION_AAL,
  INVENTORY_DEFINITION_RAAL,
  INVENTORY_DEFINITION_VI,
  INVENTORY_DEFINITION_GN,
  INVENTORY_DEFINITION_IVL,
  INVENTORY_DEFINITION_VT,
  INVENTORY_DEFINITION_DF,
  INVENTORY_DEFINITION_SIM,
  INVENTORY_DEFINITION_CUSTOMER,
  INVENTORY_TRANSACTION,
  INVENTORY_TRANSACTION_PR,
  INVENTORY_TRANSACTION_PRA,
  INVENTORY_TRANSACTION_GAR,
  INVENTORY_TRANSACTION_PO,
  INVENTORY_TRANSACTION_POC,
  INVENTORY_TRANSACTION_POA,
  INVENTORY_TRANSACTION_MIN,
  INVENTORY_TRANSACTION_SRN,
  INVENTORY_TRANSACTION_PRN,
  INVENTORY_TRANSACTION_ITR,
  INVENTORY_TRANSACTION_ISI,
  INVENTORY_TRANSACTION_ISR,
  INVENTORY_TRANSACTION_SALE_RETURN_NOTE,
  INVENTORY_TRANSACTION_SIN,
  INVENTORY_TRANSACTION_SAN,
  INVENTORY_TRANSACTION_VAN,
  INVENTORY_REPORTS,
  INVENTORY_REPORTS_SWIM,
  INVENTORY_REPORTS_EWIL,
  INVENTORY_REPORTS_EWV,
  INVENTORY_REPORTS_SIS,
  INVENTORY_REPORTS_SPBW,
  INVENTORY_REPORTS_SPB,
  INVENTORY_REPORTS_SM,
  INVENTORY_REPORTS_MWSP,
  INVENTORY_REPORTS_SSR,
  INVENTORY_REPORTS_TTR,
  INVENTORY_REPORTS_PSR,
  INVENTORY_REPORTS_TV,
  INVENTORY_REPORTS_IVCW,
  INVENTORY_REPORTS_FR,
  INVENTORY_REPORTS_UIR,
  INVENTORY_POS,
  INVENTORY_POS_SALES,
  INVENTORY_POS_SR,
  INVENTORY_POS_OS,
  INVENTORY_POS_SM,
  INVENTORY_POS_SSR,
  INVENTORY_POS_IWSR,
  INVENTORY_POS_IOD,
  INVENTORY_POS_IS,
};
