const PAYROLL_DASHBOARD_KEY = 'PAYROLL_DASHBOARD';

const PAYROLL_HR = 'PAYROLL_HR';
const PAYROLL_HR_ET = 'PAYROLL_HR_ET';
const PAYROLL_HR_EC = 'PAYROLL_HR_EC';
const PAYROLL_HR_LOCATIONS = 'PAYROLL_HR_LOCATIONS';
const PAYROLL_HR_BANKS = 'PAYROLL_HR_BANKS';
const PAYROLL_HR_DESIGNATIONS = 'PAYROLL_HR_DESIGNATIONS';
const PAYROLL_HR_EG = 'PAYROLL_HR_EG';
const PAYROLL_HR_EOBI = 'PAYROLL_HR_EOBI';
const PAYROLL_HR_EBI = 'PAYROLL_HR_EBI';

const PAYROLL_DEFINITIONS = 'PAYROLL_DEFINITIONS';
const PAYROLL_DEFINITIONS_ADVANCE_TYPE = 'PAYROLL_DEFINITIONS_ADVANCE_TYPE';
const PAYROLL_DEFINITIONS_ADDITION_TYPE = 'PAYROLL_DEFINITIONS_ADDITION_TYPE';
const PAYROLL_DEFINITIONS_ALLOWANCES_TYPE = 'PAYROLL_DEFINITIONS_ALLOWANCES_TYPE';
const PAYROLL_DEFINITIONS_DT = 'PAYROLL_DEFINITIONS_DT';
const PAYROLL_DEFINITIONS_LT = 'PAYROLL_DEFINITIONS_LT';
const PAYROLL_DEFINITIONS_BT = 'PAYROLL_DEFINITIONS_BT';
const PAYROLL_DEFINITIONS_TAX = 'PAYROLL_DEFINITIONS_TAX';
const PAYROLL_DEFINITIONS_TAX_TC = 'PAYROLL_DEFINITIONS_TAX_TC';
const PAYROLL_DEFINITIONS_TAX_TC_CD = 'PAYROLL_DEFINITIONS_TAX_TC_CD';
const PAYROLL_DEFINITIONS_TAX_TC_SI = 'PAYROLL_DEFINITIONS_TAX_TC_SI';
const PAYROLL_DEFINITIONS_ELR = 'PAYROLL_DEFINITIONS_ELR';
const PAYROLL_DEFINITIONS_ELR_LT = 'PAYROLL_DEFINITIONS_ELR_LT';
const PAYROLL_DEFINITIONS_ELR_AS = 'PAYROLL_DEFINITIONS_ELR_AS';
const PAYROLL_DEFINITIONS_PF_OB = 'PAYROLL_DEFINITIONS_PF_OB';
const PAYROLL_DEFINITIONS_PF_YP = 'PAYROLL_DEFINITIONS_PF_YP';
const PAYROLL_DEFINITIONS_PS = 'PAYROLL_DEFINITIONS_PS';

const PAYROLL_TRANSACTIONS = 'PAYROLL_TRANSACTIONS';
const PAYROLL_TRANSACTIONS_ADVANCE = 'PAYROLL_TRANSACTIONS_ADVANCE';
const PAYROLL_TRANSACTIONS_ADDITION = 'PAYROLL_TRANSACTIONS_ADDITION';
const PAYROLL_TRANSACTIONS_DEDUCTION = 'PAYROLL_TRANSACTIONS_DEDUCTION';
const PAYROLL_TRANSACTIONS_LI = 'PAYROLL_TRANSACTIONS_LI';
const PAYROLL_TRANSACTIONS_LE = 'PAYROLL_TRANSACTIONS_LE';
const PAYROLL_TRANSACTIONS_HONORARIUM = 'PAYROLL_TRANSACTIONS_HONORARIUM';
const PAYROLL_TRANSACTIONS_RAR = 'PAYROLL_TRANSACTIONS_RAR';
const PAYROLL_TRANSACTIONS_OP = 'PAYROLL_TRANSACTIONS_OP';
const PAYROLL_TRANSACTIONS_TA = 'PAYROLL_TRANSACTIONS_TA';
const PAYROLL_TRANSACTIONS_RESIGN = 'PAYROLL_TRANSACTIONS_RESIGN';
const PAYROLL_TRANSACTIONS_EFA = 'PAYROLL_TRANSACTIONS_EFA';
const PAYROLL_TRANSACTIONS_FINANCIAL = 'PAYROLL_TRANSACTIONS_FINANCIAL';
const PAYROLL_TRANSACTIONS_FINANCIAL_OI = 'PAYROLL_TRANSACTIONS_FINANCIAL_OI';
const PAYROLL_TRANSACTIONS_FINANCIAL_SS = 'PAYROLL_TRANSACTIONS_FINANCIAL_SS';
const PAYROLL_TRANSACTIONS_FINANCIAL_SH = 'PAYROLL_TRANSACTIONS_FINANCIAL_SH';
const PAYROLL_TRANSACTIONS_FINANCIAL_SC = 'PAYROLL_TRANSACTIONS_FINANCIAL_SC';
const PAYROLL_TRANSACTIONS_ELR = 'PAYROLL_TRANSACTIONS_ELR';
const PAYROLL_TRANSACTIONS_ELR_AR = 'PAYROLL_TRANSACTIONS_ELR_AR';
const PAYROLL_TRANSACTIONS_ELR_EEPL = 'PAYROLL_TRANSACTIONS_ELR_EEPL';

const PAYROLL_REPORTS = 'PAYROLL_REPORTS';
const PAYROLL_REPORTS_LISTING = 'PAYROLL_REPORTS_LISTING';
const PAYROLL_REPORTS_LISTING_ADVANCE_TYPE = 'PAYROLL_REPORTS_LISTING_ADVANCE_TYPE';
const PAYROLL_REPORTS_LISTING_ALLOWANCE_TYPE = 'PAYROLL_REPORTS_LISTING_ALLOWANCE_TYPE';
const PAYROLL_REPORTS_LISTING_BONUS_TYPE = 'PAYROLL_REPORTS_LISTING_BONUS_TYPE';
const PAYROLL_REPORTS_LISTING_DT = 'PAYROLL_REPORTS_LISTING_DT';
const PAYROLL_REPORTS_LISTING_LT = 'PAYROLL_REPORTS_LISTING_LT';
const PAYROLL_REPORTS_LISTING_LEAVE_TYPE = 'PAYROLL_REPORTS_LISTING_LEAVE_TYPE';
const PAYROLL_REPORTS_PR = 'PAYROLL_REPORTS_PR';
const PAYROLL_REPORTS_PR_AS = 'PAYROLL_REPORTS_PR_AS';
const PAYROLL_REPORTS_PR_DS = 'PAYROLL_REPORTS_PR_DS';
const PAYROLL_REPORTS_PR_LWPS = 'PAYROLL_REPORTS_PR_LWPS';
const PAYROLL_REPORTS_PR_REA = 'PAYROLL_REPORTS_PR_REA';
const PAYROLL_REPORTS_PR_RED = 'PAYROLL_REPORTS_PR_RED';
const PAYROLL_REPORTS_PR_JCEA = 'PAYROLL_REPORTS_PR_JCEA';
const PAYROLL_REPORTS_PR_JCED = 'PAYROLL_REPORTS_PR_JCED';
const PAYROLL_REPORTS_PR_SCEA = 'PAYROLL_REPORTS_PR_SCEA';
const PAYROLL_REPORTS_PR_SCED = 'PAYROLL_REPORTS_PR_SCED';
const PAYROLL_REPORTS_PR_SRA = 'PAYROLL_REPORTS_PR_SRA';
const PAYROLL_REPORTS_PR_SRD = 'PAYROLL_REPORTS_PR_SRD';
const PAYROLL_REPORTS_PR_SS = 'PAYROLL_REPORTS_PR_SS';
const PAYROLL_REPORTS_PR_LFS = 'PAYROLL_REPORTS_PR_LFS';
const PAYROLL_REPORTS_PR_LFB = 'PAYROLL_REPORTS_PR_LFB';
const PAYROLL_REPORTS_PR_CSR = 'PAYROLL_REPORTS_PR_CSR';

export {
  PAYROLL_DASHBOARD_KEY,
  PAYROLL_HR,
  PAYROLL_HR_ET,
  PAYROLL_HR_EC,
  PAYROLL_HR_LOCATIONS,
  PAYROLL_HR_BANKS,
  PAYROLL_HR_DESIGNATIONS,
  PAYROLL_HR_EG,
  PAYROLL_HR_EOBI,
  PAYROLL_HR_EBI,
  PAYROLL_DEFINITIONS,
  PAYROLL_DEFINITIONS_ADVANCE_TYPE,
  PAYROLL_DEFINITIONS_ADDITION_TYPE,
  PAYROLL_DEFINITIONS_ALLOWANCES_TYPE,
  PAYROLL_DEFINITIONS_DT,
  PAYROLL_DEFINITIONS_LT,
  PAYROLL_DEFINITIONS_BT,
  PAYROLL_DEFINITIONS_TAX,
  PAYROLL_DEFINITIONS_TAX_TC,
  PAYROLL_DEFINITIONS_TAX_TC_CD,
  PAYROLL_DEFINITIONS_TAX_TC_SI,
  PAYROLL_DEFINITIONS_ELR,
  PAYROLL_DEFINITIONS_ELR_LT,
  PAYROLL_DEFINITIONS_ELR_AS,
  PAYROLL_DEFINITIONS_PF_OB,
  PAYROLL_DEFINITIONS_PF_YP,
  PAYROLL_DEFINITIONS_PS,
  PAYROLL_TRANSACTIONS,
  PAYROLL_TRANSACTIONS_ADVANCE,
  PAYROLL_TRANSACTIONS_ADDITION,
  PAYROLL_TRANSACTIONS_DEDUCTION,
  PAYROLL_TRANSACTIONS_LI,
  PAYROLL_TRANSACTIONS_LE,
  PAYROLL_TRANSACTIONS_HONORARIUM,
  PAYROLL_TRANSACTIONS_RAR,
  PAYROLL_TRANSACTIONS_OP,
  PAYROLL_TRANSACTIONS_TA,
  PAYROLL_TRANSACTIONS_RESIGN,
  PAYROLL_TRANSACTIONS_EFA,
  PAYROLL_TRANSACTIONS_FINANCIAL,
  PAYROLL_TRANSACTIONS_FINANCIAL_OI,
  PAYROLL_TRANSACTIONS_FINANCIAL_SS,
  PAYROLL_TRANSACTIONS_FINANCIAL_SH,
  PAYROLL_TRANSACTIONS_FINANCIAL_SC,
  PAYROLL_TRANSACTIONS_ELR,
  PAYROLL_TRANSACTIONS_ELR_AR,
  PAYROLL_TRANSACTIONS_ELR_EEPL,
  PAYROLL_REPORTS,
  PAYROLL_REPORTS_LISTING,
  PAYROLL_REPORTS_LISTING_ADVANCE_TYPE,
  PAYROLL_REPORTS_LISTING_ALLOWANCE_TYPE,
  PAYROLL_REPORTS_LISTING_BONUS_TYPE,
  PAYROLL_REPORTS_LISTING_DT,
  PAYROLL_REPORTS_LISTING_LT,
  PAYROLL_REPORTS_LISTING_LEAVE_TYPE,
  PAYROLL_REPORTS_PR,
  PAYROLL_REPORTS_PR_AS,
  PAYROLL_REPORTS_PR_DS,
  PAYROLL_REPORTS_PR_LWPS,
  PAYROLL_REPORTS_PR_REA,
  PAYROLL_REPORTS_PR_RED,
  PAYROLL_REPORTS_PR_JCEA,
  PAYROLL_REPORTS_PR_JCED,
  PAYROLL_REPORTS_PR_SCEA,
  PAYROLL_REPORTS_PR_SCED,
  PAYROLL_REPORTS_PR_SRA,
  PAYROLL_REPORTS_PR_SRD,
  PAYROLL_REPORTS_PR_SS,
  PAYROLL_REPORTS_PR_LFS,
  PAYROLL_REPORTS_PR_LFB,
  PAYROLL_REPORTS_PR_CSR,
};
