export const FORM_NAMES = {
  PR_HR_EMPLOYEE_TYPE_FORM: 'PR_HR_EMPLOYEE_TYPE_FORM',
  PR_HR_EMPLOYEE_CATEGORY_FORM: 'PR_HR_EMPLOYEE_CATEGORY_FORM',
  PR_HR_LOCATION_FORM: 'PR_HR_LOCATION_FORM',
  PR_HR_BANK_FORM: 'PR_HR_BANK_FORM',
  PR_HR_DESIGNATION_FORM: 'PR_HR_DESIGNATION_FORM',
  PR_HR_EXECUTIVE_GRADE_PARENT_FORM: 'PR_HR_EXECUTIVE_GRADE_PARENT_FORM',
  PR_HR_EXECUTIVE_GRADE_CHILD_FORM: 'PR_HR_EXECUTIVE_GRADE_CHILD_FORM',
  PR_HR_EOBI_FORM: 'PR_HR_EOBI_FORM',
  PR_HR_EBI_FORM: 'PR_HR_EBI_FORM',
  PR_DEFINITIONS_ADVANCE_TYPE_FORM: 'PR_DEFINITIONS_ADVANCE_TYPE_FORM',
  PR_DEFINITIONS_ADDITION_TYPE_FORM: 'PR_DEFINITIONS_ADDITION_TYPE_FORM',
};
