import * as routes from 'router/routes/payrollRoutes';
import * as keys from 'router/routeKeys/payrollRoutesKeys';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faChartLine } from '@fortawesome/free-solid-svg-icons';

export const sideMenu = [
  {
    name: 'Dashboard',
    key: keys.PAYROLL_DASHBOARD_KEY,
    icon: <FontAwesomeIcon icon={faChartLine} />,
    url: routes.PAYROLL_DASHBOARD,
    hasSubMenu: false,
    hasPermission: true,
    menu: [],
  },
  {
    name: 'Human Resource',
    key: keys.PAYROLL_HR,
    icon: <FontAwesomeIcon icon={faChartLine} />,
    url: '',
    hasSubMenu: true,
    hasPermission: true,
    menu: [
      {
        name: 'Employee Type',
        key: keys.PAYROLL_HR_ET,
        icon: '',
        url: routes.HR_ET,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Employee Category',
        key: keys.PAYROLL_HR_EC,
        icon: '',
        url: routes.HR_EC,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Offices / Locations',
        key: keys.PAYROLL_HR_LOCATIONS,
        icon: '',
        url: routes.HR_LOCATIONS,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Banks',
        key: keys.PAYROLL_HR_BANKS,
        icon: '',
        url: routes.HR_BANKS,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Designations',
        key: keys.PAYROLL_HR_DESIGNATIONS,
        icon: '',
        url: routes.HR_DESIGNATIONS,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Executive Grade',
        key: keys.PAYROLL_HR_EG,
        icon: '',
        url: routes.HR_EG,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'EOBI',
        key: keys.PAYROLL_HR_EOBI,
        icon: '',
        url: routes.HR_EOBI,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Employee Basic Info',
        key: keys.PAYROLL_HR_EBI,
        icon: '',
        url: routes.HR_EBI,
        hasSubMenu: false,
        hasPermission: true,
      },
    ],
  },
  {
    name: 'Definitions',
    key: keys.PAYROLL_DEFINITIONS,
    icon: <FontAwesomeIcon icon={faChartLine} />,
    url: '',
    hasSubMenu: true,
    hasPermission: true,
    menu: [
      {
        name: 'Advance Type',
        key: keys.PAYROLL_DEFINITIONS_ADVANCE_TYPE,
        icon: '',
        url: routes.DEFINITIONS_ADVANCE_TYPE,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Addition Type',
        key: keys.PAYROLL_DEFINITIONS_ADDITION_TYPE,
        icon: '',
        url: routes.DEFINITIONS_ADDITION_TYPE,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Allowances Type',
        key: keys.PAYROLL_DEFINITIONS_ALLOWANCES_TYPE,
        icon: '',
        url: routes.DEFINITIONS_ALLOWANCES_TYPE,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Deduction Type',
        key: keys.PAYROLL_DEFINITIONS_DT,
        icon: '',
        url: routes.DEFINITIONS_DT,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Loan Type',
        key: keys.PAYROLL_DEFINITIONS_LT,
        icon: '',
        url: routes.DEFINITIONS_LT,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Bonus Type',
        key: keys.PAYROLL_DEFINITIONS_BT,
        icon: '',
        url: routes.DEFINITIONS_BT,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Tax',
        key: keys.PAYROLL_DEFINITIONS_TAX,
        icon: '',
        url: '',
        hasSubMenu: true,
        hasPermission: true,
        menu: [
          {
            name: 'Tax Credits',
            key: keys.PAYROLL_DEFINITIONS_TAX_TC,
            icon: '',
            url: '',
            hasSubMenu: true,
            hasPermission: true,
            menu: [
              {
                name: 'Charitable Donations',
                key: keys.PAYROLL_DEFINITIONS_TAX_TC_CD,
                icon: '',
                url: routes.DEFINITIONS_TAX_TC_CD,
                hasSubMenu: false,
                hasPermission: true,
              },
              {
                name: 'Share Investments',
                key: keys.PAYROLL_DEFINITIONS_TAX_TC_SI,
                icon: '',
                url: routes.DEFINITIONS_TAX_TC_SI,
                hasSubMenu: false,
                hasPermission: true,
              },
            ],
          },
        ],
      },
      {
        name: 'Employee Leave Record',
        key: keys.PAYROLL_DEFINITIONS_ELR,
        icon: '',
        url: '',
        hasSubMenu: true,
        hasPermission: true,
        menu: [
          {
            name: 'Leave Type',
            key: keys.PAYROLL_DEFINITIONS_ELR_LT,
            icon: '',
            url: routes.DEFINITIONS_ELR_LT,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Attendance Status',
            key: keys.PAYROLL_DEFINITIONS_ELR_AS,
            icon: '',
            url: routes.DEFINITIONS_ELR_AS,
            hasSubMenu: false,
            hasPermission: true,
          },
        ],
      },
      {
        name: 'PF Opening Balance',
        key: keys.PAYROLL_DEFINITIONS_PF_OB,
        icon: '',
        url: routes.DEFINITIONS_PF_OB,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'PF Yearly Profit',
        key: keys.PAYROLL_DEFINITIONS_PF_YP,
        icon: '',
        url: routes.DEFINITIONS_PF_YP,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Payroll System',
        key: keys.PAYROLL_DEFINITIONS_PS,
        icon: '',
        url: routes.DEFINITIONS_PS,
        hasSubMenu: false,
        hasPermission: true,
      },
    ],
  },
  {
    name: 'Transactions',
    key: keys.PAYROLL_TRANSACTIONS,
    icon: <FontAwesomeIcon icon={faChartLine} />,
    url: '',
    hasSubMenu: true,
    hasPermission: true,
    menu: [
      {
        name: 'Advance',
        key: keys.PAYROLL_TRANSACTIONS_ADVANCE,
        icon: '',
        url: routes.TRANSACTIONS_ADVANCE,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Addition',
        key: keys.PAYROLL_TRANSACTIONS_ADDITION,
        icon: '',
        url: routes.TRANSACTIONS_ADDITION,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Deduction',
        key: keys.PAYROLL_TRANSACTIONS_DEDUCTION,
        icon: '',
        url: routes.TRANSACTIONS_DEDUCTION,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Loan Issues',
        key: keys.PAYROLL_TRANSACTIONS_LI,
        icon: '',
        url: routes.TRANSACTIONS_LI,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Leave Encashment',
        key: keys.PAYROLL_TRANSACTIONS_LE,
        icon: '',
        url: routes.TRANSACTIONS_LE,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Honorarium',
        key: keys.PAYROLL_TRANSACTIONS_HONORARIUM,
        icon: '',
        url: routes.TRANSACTIONS_HONORARIUM,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Rest And Recreation',
        key: keys.PAYROLL_TRANSACTIONS_RAR,
        icon: '',
        url: routes.TRANSACTIONS_RAR,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Other Payments',
        key: keys.PAYROLL_TRANSACTIONS_OP,
        icon: '',
        url: routes.TRANSACTIONS_OP,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Tax Adjustment',
        key: keys.PAYROLL_TRANSACTIONS_TA,
        icon: '',
        url: routes.TRANSACTIONS_TA,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Resign / Terminate / Contract End',
        key: keys.PAYROLL_TRANSACTIONS_RESIGN,
        icon: '',
        url: routes.TRANSACTIONS_RESIGN,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Employee Fuel Adjustment',
        key: keys.PAYROLL_TRANSACTIONS_EFA,
        icon: '',
        url: routes.TRANSACTIONS_EFA,
        hasSubMenu: false,
        hasPermission: true,
      },
      {
        name: 'Financial',
        key: keys.PAYROLL_TRANSACTIONS_FINANCIAL,
        icon: '',
        url: '',
        hasSubMenu: true,
        hasPermission: true,
        menu: [
          {
            name: 'Other Incomes',
            key: keys.PAYROLL_TRANSACTIONS_FINANCIAL_OI,
            icon: '',
            url: routes.TRANSACTIONS_FINANCIAL_OI,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Salary Schemes',
            key: keys.PAYROLL_TRANSACTIONS_FINANCIAL_SS,
            icon: '',
            url: routes.TRANSACTIONS_FINANCIAL_SS,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Salary History',
            key: keys.PAYROLL_TRANSACTIONS_FINANCIAL_SH,
            icon: '',
            url: routes.TRANSACTIONS_FINANCIAL_SH,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Salary Calculation',
            key: keys.PAYROLL_TRANSACTIONS_FINANCIAL_SC,
            icon: '',
            url: routes.TRANSACTIONS_FINANCIAL_SC,
            hasSubMenu: false,
            hasPermission: true,
          },
        ],
      },
      {
        name: 'Employee Leave Record',
        key: keys.PAYROLL_TRANSACTIONS_ELR,
        icon: '',
        url: '',
        hasSubMenu: true,
        hasPermission: true,
        menu: [
          {
            name: 'Attendance Register',
            key: keys.PAYROLL_TRANSACTIONS_ELR_AR,
            icon: '',
            url: routes.TRANSACTIONS_ELR_AR,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Employee EX Pakistan Leave',
            key: keys.PAYROLL_TRANSACTIONS_ELR_EEPL,
            icon: '',
            url: routes.TRANSACTIONS_ELR_EEPL,
            hasSubMenu: false,
            hasPermission: true,
          },
        ],
      },
    ],
  },
  {
    name: 'Reports',
    key: keys.PAYROLL_REPORTS,
    icon: <FontAwesomeIcon icon={faChartLine} />,
    url: '',
    hasSubMenu: true,
    hasPermission: true,
    menu: [
      {
        name: 'Listing',
        key: keys.PAYROLL_REPORTS_LISTING,
        icon: '',
        url: '',
        hasSubMenu: true,
        hasPermission: true,
        menu: [
          {
            name: 'Advance Type',
            key: keys.PAYROLL_REPORTS_LISTING_ADVANCE_TYPE,
            icon: '',
            url: routes.REPORTS_LISTING_ADVANCE_TYPE,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Allowance Type',
            key: keys.PAYROLL_REPORTS_LISTING_ALLOWANCE_TYPE,
            icon: '',
            url: routes.REPORTS_LISTING_ALLOWANCE_TYPE,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Bonus Type',
            key: keys.PAYROLL_REPORTS_LISTING_BONUS_TYPE,
            icon: '',
            url: routes.REPORTS_LISTING_BONUS_TYPE,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Deduction Type',
            key: keys.PAYROLL_REPORTS_LISTING_DT,
            icon: '',
            url: routes.REPORTS_LISTING_DT,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Loan Type',
            key: keys.PAYROLL_REPORTS_LISTING_LT,
            icon: '',
            url: routes.REPORTS_LISTING_LT,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Leave Type',
            key: keys.PAYROLL_REPORTS_LISTING_LEAVE_TYPE,
            icon: '',
            url: routes.REPORTS_LISTING_LEAVE_TYPE,
            hasSubMenu: false,
            hasPermission: true,
          },
        ],
      },
      {
        name: 'Pay Register',
        key: keys.PAYROLL_REPORTS_PR,
        icon: '',
        url: '',
        hasSubMenu: true,
        hasPermission: true,
        menu: [
          {
            name: 'Allowance Summary',
            key: keys.PAYROLL_REPORTS_PR_AS,
            icon: '',
            url: routes.REPORTS_PR_AS,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Deductions Summary',
            key: keys.PAYROLL_REPORTS_PR_DS,
            icon: '',
            url: routes.REPORTS_PR_DS,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Location Wise Pay Summary',
            key: keys.PAYROLL_REPORTS_PR_LWPS,
            icon: '',
            url: routes.REPORTS_PR_LWPS,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Regular Employees (Allowances)',
            key: keys.PAYROLL_REPORTS_PR_REA,
            icon: '',
            url: routes.REPORTS_PR_REA,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Regular Employees (Deductions)',
            key: keys.PAYROLL_REPORTS_PR_RED,
            icon: '',
            url: routes.REPORTS_PR_RED,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Junior Contract Employees (Allowances)',
            key: keys.PAYROLL_REPORTS_PR_JCEA,
            icon: '',
            url: routes.REPORTS_PR_JCEA,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Junior Contract Employees (Deductions)',
            key: keys.PAYROLL_REPORTS_PR_JCED,
            icon: '',
            url: routes.REPORTS_PR_JCED,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Senior Contract Employees (Allowance)',
            key: keys.PAYROLL_REPORTS_PR_SCEA,
            icon: '',
            url: routes.REPORTS_PR_SCEA,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Senior Contract Employees (Deduction)',
            key: keys.PAYROLL_REPORTS_PR_SCED,
            icon: '',
            url: routes.REPORTS_PR_SCED,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Salary Reconciliation (Allowances)',
            key: keys.PAYROLL_REPORTS_PR_SRA,
            icon: '',
            url: routes.REPORTS_PR_SRA,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Salary Reconciliation (Deductions)',
            key: keys.PAYROLL_REPORTS_PR_SRD,
            icon: '',
            url: routes.REPORTS_PR_SRD,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Salary Statement (Salary Slip)',
            key: keys.PAYROLL_REPORTS_PR_SS,
            icon: '',
            url: routes.REPORTS_PR_SS,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Letter For Salary',
            key: keys.PAYROLL_REPORTS_PR_LFS,
            icon: '',
            url: routes.REPORTS_PR_LFS,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Letter For Bonus',
            key: keys.PAYROLL_REPORTS_PR_LFB,
            icon: '',
            url: routes.REPORTS_PR_LFB,
            hasSubMenu: false,
            hasPermission: true,
          },
          {
            name: 'Consolidate Salary Report',
            key: keys.PAYROLL_REPORTS_PR_CSR,
            icon: '',
            url: routes.REPORTS_PR_CSR,
            hasSubMenu: false,
            hasPermission: true,
          },
        ],
      },
    ],
  },
];
