export const PR_HR_EMPLOYEE_TYPES_GET_LIST = 'PR_HR_EMPLOYEE_TYPES_GET_LIST';
export const PR_HR_EMPLOYEE_CATEGORIES_GET_LIST = 'PR_HR_EMPLOYEE_CATEGORIES_GET_LIST';
export const PR_HR_LOCATIONS_GET_LIST = 'PR_HR_LOCATIONS_GET_LIST';
export const PR_HR_BANKS_GET_LIST = 'PR_HR_BANKS_GET_LIST';
export const PR_HR_DESIGNATIONS_GET_LIST = 'PR_HR_DESIGNATIONS_GET_LIST';
export const PR_HR_EXECUTIVE_GRADES_GET_LIST = 'PR_HR_EXECUTIVE_GRADES_GET_LIST';
export const PR_HR_EOBI_GET_LIST = 'PR_HR_EOBI_GET_LIST';
export const PR_HR_EBI_GET_LIST = 'PR_HR_EBI_GET_LIST';
